import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
Src/ft32f0xx_comp.c
Src/ft32f0xx_crc.c
Src/ft32f0xx_crs.c
Src/ft32f0xx_debug.c
Src/ft32f0xx_div.c
Src/ft32f0xx_dma.c
Src/ft32f0xx_exti.c
Src/ft32f0xx_gpio.c
Src/ft32f0xx_iwdg.c
Src/ft32f0xx_misc.c
Src/ft32f0xx_opa.c
Src/ft32f0xx_pwr.c
Src/ft32f0xx_rcc.c
Src/ft32f0xx_syscfg.c
Src/ft32f0xx_tim.c
""")

if GetDepend(['RT_USING_SERIAL']):
    src += ['Src/ft32f0xx_usart.c']

if GetDepend(['RT_USING_I2C']):
    src += ['Src/ft32f0xx_i2c.c']

if GetDepend(['RT_USING_SPI']):
    src += ['Src/ft32f0xx_spi.c']

if GetDepend(['RT_USING_ADC']):
    src += ['Src/ft32f0xx_adc.c']

if GetDepend(['RT_USING_RTC']):
    src += ['Src/ft32f0xx_rtc.c']

if GetDepend(['RT_USING_WDT']):
    src += ['Src/ft32f0xx_wwdg.c']

if GetDepend(['BSP_USING_ON_CHIP_FLASH']):
    src += ['Src/ft32f0xx_flash.c']

path = [cwd + '/Inc',
    cwd + '/templates/Inc']

CPPDEFINES = ['USE_STDPERIPH_DRIVER']

group = DefineGroup('Libraries', src, depend = ['SOC_SERIES_FT32F0'], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
